### ISSUE TITLE
Odd problem with cli

### ISSUE THREAD

**Issue by lucassus** [lucassus/mongo_browser#66]
```
/home/lucassus/.rvm/gems/ruby-1.9.3-p194-perf/gems/methadone-1.2.2/lib/methadone/cli_logger.rb:53:in `block in proxy_method': undefined method `formatter=' for nil:NilClass (NoMethodError)
    from /home/lucassus/.rvm/gems/ruby-1.9.3-p194-perf/gems/activesupport-3.2.9/lib/active_support/core_ext/logger.rb:73:in `initialize'
    from /home/lucassus/.rvm/gems/ruby-1.9.3-p194-perf/gems/methadone-1.2.2/lib/methadone/cli_logger.rb:85:in `initialize'
    from /home/lucassus/.rvm/gems/ruby-1.9.3-p194-perf/gems/methadone-1.2.2/lib/methadone/cli_logging.rb:37:in `new'
    from /home/lucassus/.rvm/gems/ruby-1.9.3-p194-perf/gems/methadone-1.2.2/lib/methadone/cli_logging.rb:37:in `logger'
    from /home/lucassus/.rvm/gems/ruby-1.9.3-p194-perf/gems/methadone-1.2.2/lib/methadone/main.rb:376:in `rescue in call_main'
    from /home/lucassus/.rvm/gems/ruby-1.9.3-p194-perf/gems/methadone-1.2.2/lib/methadone/main.rb:366:in `call_main'
    from /home/lucassus/.rvm/gems/ruby-1.9.3-p194-perf/gems/methadone-1.2.2/lib/methadone/main.rb:165:in `go!'
    from /home/lucassus/.rvm/gems/ruby-1.9.3-p194-perf/gems/mongo_browser-0.2.1.rc1/bin/mongo_browser:52:in `<class:App>'
    from /home/lucassus/.rvm/gems/ruby-1.9.3-p194-perf/gems/mongo_browser-0.2.1.rc1/bin/mongo_browser:8:in `<top (required)>'
    from /home/lucassus/.rvm/gems/ruby-1.9.3-p194-perf/bin/mongo_browser:19:in `load'
    from /home/lucassus/.rvm/gems/ruby-1.9.3-p194-perf/bin/mongo_browser:19:in `<main>'
    from /home/lucassus/.rvm/gems/ruby-1.9.3-p194-perf/bin/ruby_noexec_wrapper:14:in `eval'
    from /home/lucassus/.rvm/gems/ruby-1.9.3-p194-perf/bin/ruby_noexec_wrapper:14:in `<main>'
```

**Comment by lucassus** [comment]
Use Vegas Luke https://github.com/quirkey/vegas, https://github.com/bobthecow/genghis/blob/master/bin/genghisapp
